spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///springcloud_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.bdqn.domain

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,
                    http://eureka7002.com:7002/eureka,
  instance:
    prefer-ip-address: true # 使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 该实例给服务中心发送心跳的间隔时间，用于表明该服务实例可用
    lease-renewal-interval-in-seconds: 5
    # 服务中心删除此服务实例的等待时间(秒为单位),时间间隔为最后一次服务中心接受到的心跳时间
    lease-expiration-duration-in-seconds: 20
